Scripts/climbing/climbing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('journal/', include('journal.urls')),
    path('admin/', admin.site.urls),
]

Scripts/climbing/journal/urls.py
from django.urls import path

from . import views

app_name='journal'
urlpatterns = [
    path('', views.index, name='index'),
    path('locations/', views.log_by_location, name='location_overview'),
    path('date/', views.log_by_date, name='log_by_date'),
    path('locations/<int:location_id>', views.log_by_location, name='log_by_location'),
]

Scripts/climbing/journal/models.py
from django.db import models

class Location(models.Model):
    location_type = models.CharField(max_length=200)
    name = models.CharField(max_length=10000)
    parent_location = models.ForeignKey('self',
                                        null=True,
                                        blank=True,
                                        on_delete=models.SET_NULL,
                                        related_name='child_location')

    def __str__(self):
        if not self.parent_location:
            return self.name
        return str(self.parent_location) + " * " + self.name

# class Problem(Location):
#     grade = models.CharField(max_length=100)
#     sent = models.BoolField()
#     project = models.BoolField()

#     def __str__(self):
#         if not self.parent_location:
#             return self.name
#         return str(self.parent_location) + " * " + self.name


class Note(models.Model):
    note_type = models.CharField(max_length=200)
    content = models.CharField(max_length=10000)
    location = models.ForeignKey(Location, on_delete=models.CASCADE,
                                 null=True,
                                 blank=True,
                                 related_name='notes')
    date = models.DateField()

    def __str__(self):
        return str(self.location) + ": " + str(self.date) + " - " + self.content


# Create your models here.

Scripts/climbing/journal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Location, Note
import logging
import collections
from .import_data import import_data

class SimpleLocation:
    def __init__(self):
        self.name = None
        self.children = []
        self.parent = None
        self.notes = []

def process_notes_for_date(notes_for_date):
    locations_for_date = collections.defaultdict(lambda: SimpleLocation())
    root_locations_for_date = set()
    for n in notes_for_date:
        simple_location = locations_for_date[n.location]
        simple_location.name = n.location.name
        simple_location.notes += [n]

        location = n.location
        while location.parent_location:
            parent_simple_location = locations_for_date[location.parent_location]
            parent_simple_location.name = location.parent_location.name

            if simple_location not in parent_simple_location.children:
                parent_simple_location.children += [simple_location]
            simple_location.parent = parent_simple_location

            location = location.parent_location
            simple_location = simple_location.parent

        locations_for_date[location].name = location.name

        root_locations_for_date.add(simple_location)

        print (n.date, root_locations_for_date)

    return (n.date, root_locations_for_date)

def log_by_date(request):
    print('log_by_date')
    notes = Note.objects.all().order_by('date').reverse()
    import_data()

    notes_for_date = []
    notes_collected = []

    for note in notes:
        if not notes_for_date or notes_for_date[0].date == note.date:
            notes_for_date += [note]
        else:
            notes_collected += [process_notes_for_date(notes_for_date)]
            notes_for_date = [note]
    notes_collected += [process_notes_for_date(notes_for_date)]

    for l in notes_collected:
        print(l[0])

    print(notes_collected[0])
    context = {'notes' : notes,
               'notes_collected': notes_collected}

    return render(request, "date.html", context)

def log_by_location(request,location_id = None):
    print ('log_by_location', location_id)
    locations = []
    notes = {}
    root_locations = Location.objects.filter(parent_location=None)
    if not location_id:
        locations = root_locations
        print(locations[0])
    else:
        locations = Location.objects.filter(id=location_id)

    for location in root_locations:
        notes[location.id] = Note.objects.filter(location_id=location.id)
        for child_location in location.child_location.get_queryset():
            notes[child_location.id] = Note.objects.filter(location_id=child_location.id)
    print(notes)
    context = {'locations' : locations,
               'root_locations' : root_locations,
               'current_location' : locations[0],
               'notes' : notes}

    return render(request, "location_list.html", context)

def location_list(request):
    return log_by_location(request, None)

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

# Create your views here.

Scripts/climbing/journal/templates/date.html
<ul>
{% for date, root_locations in notes_collected %}
<li> {{date}} </li>
<ul>
{% for location in root_locations %}
{% include "date_location.html" %}
{% endfor %}
</ul>
{% endfor %}
</ul>

Scripts/climbing/journal/templates/date_location.html
<li> {{location.name}}
{% for note in location.notes %}
<b>{{note.content}} </b>
{% endfor %}

<ul>
{% for location in location.children %}
{% include "date_location.html" %}
{% endfor %}
</ul>
</li>

Scripts/climbing/journal/templates/location_list.html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.split {
  z-index: 1;
  top: 0;
  padding-top: 20px;
}
.left {
  float: left
}
.right {
    width: 70%;
    background-color: #ffffff;
}
body {
    background-color: #f1f1f1;
}
</style>
</head>
<body>


<table>
  <tr>
    <td class = "split left">
      <div>
        {% include "navigation.html" %}
      </div>
    </td>
    <td  class = "split right">
      <div>
        <ul>
          {% include "location_list_inner.html" %}
        </ul>
      </div>
    </td>
  </tr>
</table>

</body>
</html>

Scripts/climbing/journal/templates/location_list_inner.html
<ul>
{% for location in locations %}
{% include "location_list_single.html" %}
{% endfor %}
</li>

Scripts/climbing/journal/templates/location_list_navigation.html
{% include "location_list_title.html" %}
<ul>
  {% for location in location.child_location.get_queryset %}
  {% include "location_list_no_notes.html" %}
{% endfor %}
</ul>

Scripts/climbing/journal/templates/location_list_no_notes.html
<li> <a href="{% url 'journal:log_by_location' location.id %}"> {{location.name}} </a> </li>
<ul>
  {% for location in location.child_location.get_queryset %}
  {% include "location_list_no_notes.html" %}
{% endfor %}
</ul>

Scripts/climbing/journal/templates/location_list_no_notes_or_title.html
<ul>
  {% for location in location.child_location.get_queryset %}
  {% include "location_list_no_notes.html" %}
  {% endfor %}
</ul>

Scripts/climbing/journal/templates/location_list_no_title.html
<ul>
  {% for location in location.child_location.get_queryset %}
  {% include "location_list.html" %}
  {% endfor %}
</ul>

Scripts/climbing/journal/templates/location_list_single.html
{% include "location_list_title.html" %}
  <ul>
  {% for note in location.notes.get_queryset %}
      <li> <b> {{note.date}} </b> - {{note.content}} </li>
  {% endfor %}
  </ul>
  <ul>
{% for location in location.child_location.get_queryset %}
{% include "location_list_single.html" %}
{% endfor %}
</ul>

Scripts/climbing/journal/templates/location_list_title.html
<li> <a href="{% url 'journal:log_by_location' location.id %}"> {{location.name}} </a> </li>

Scripts/climbing/journal/templates/navigation.html
<ul>
{% for location in root_locations %}
{% include "navigation_inner.html" %}
{% endfor %}
</ul>

Scripts/climbing/journal/templates/navigation_inner.html
<ul>
{% if current_location == location %}
   <b> {% include "location_list_title.html" %} </b>
{% else %}
  {% include "location_list_title.html" %}
{% endif %}

{% for location in location.child_location.get_queryset %}
  {% include "navigation_inner.html" %}
{% endfor %}
</ul>